<a href="https://colab.research.google.com/github/chahatpatel2003/CSCI-167/blob/main/notebook_12_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(3)
N = 6
D = 8
X = np.random.normal(size=(D,N))
print(X)

H = 2
H_D = int(D/H)

np.random.seed(0)
omega_q1 = np.random.normal(size=(H_D,D))
omega_k1 = np.random.normal(size=(H_D,D))
omega_v1 = np.random.normal(size=(H_D,D))
beta_q1 = np.random.normal(size=(H_D,1))
beta_k1 = np.random.normal(size=(H_D,1))
beta_v1 = np.random.normal(size=(H_D,1))

omega_q2 = np.random.normal(size=(H_D,D))
omega_k2 = np.random.normal(size=(H_D,D))
omega_v2 = np.random.normal(size=(H_D,D))
beta_q2 = np.random.normal(size=(H_D,1))
beta_k2 = np.random.normal(size=(H_D,1))
beta_v2 = np.random.normal(size=(H_D,1))

omega_c = np.random.normal(size=(D,D))

def softmax_cols(data_in):
  m = np.max(data_in, axis=0, keepdims=True)
  exp_values = np.exp(data_in - m)
  denom = np.sum(exp_values, axis=0, keepdims=True)
  return exp_values / denom

def multihead_scaled_self_attention(
    X,
    omega_v1, omega_q1, omega_k1, beta_v1, beta_q1, beta_k1,
    omega_v2, omega_q2, omega_k2, beta_v2, beta_q2, beta_k2,
    omega_c
):
  def head(oq, ok, ov, bq, bk, bv):
    Q = oq @ X + bq
    K = ok @ X + bk
    V = ov @ X + bv
    S = (K.T @ Q) / np.sqrt(Q.shape[0])
    A = softmax_cols(S)
    return V @ A
  O1 = head(omega_q1, omega_k1, omega_v1, beta_q1, beta_k1, beta_v1)
  O2 = head(omega_q2, omega_k2, omega_v2, beta_q2, beta_k2, beta_v2)
  O = np.vstack([O1, O2])
  X_prime = omega_c @ O
  return X_prime

X_prime = multihead_scaled_self_attention(
    X,
    omega_v1, omega_q1, omega_k1, beta_v1, beta_q1, beta_k1,
    omega_v2, omega_q2, omega_k2, beta_v2, beta_q2, beta_k2,
    omega_c
)

np.set_printoptions(precision=3)
print("Your answer:")
print(X_prime)

print("True values:")
print("[[-21.207  -5.373 -20.933  -9.179 -11.319 -17.812]")
print(" [ -1.995   7.906 -10.516   3.452   9.863  -7.24 ]")
print(" [  5.479   1.115   9.244   0.453   5.656   7.089]")
print(" [ -7.413  -7.416   0.363  -5.573  -6.736  -0.848]")
print(" [-11.261  -9.937  -4.848  -8.915 -13.378  -5.761]")
print(" [  3.548  10.036  -2.244   1.604  12.113  -2.557]")
print(" [  4.888  -5.814   2.407   3.228  -4.232   3.71 ]")
print(" [  1.248  18.894  -6.409   3.224  19.717  -5.629]]")


[[ 1.78862847  0.43650985  0.09649747 -1.8634927  -0.2773882  -0.35475898]
 [-0.08274148 -0.62700068 -0.04381817 -0.47721803 -1.31386475  0.88462238]
 [ 0.88131804  1.70957306  0.05003364 -0.40467741 -0.54535995 -1.54647732]
 [ 0.98236743 -1.10106763 -1.18504653 -0.2056499   1.48614836  0.23671627]
 [-1.02378514 -0.7129932   0.62524497 -0.16051336 -0.76883635 -0.23003072]
 [ 0.74505627  1.97611078 -1.24412333 -0.62641691 -0.80376609 -2.41908317]
 [-0.92379202 -1.02387576  1.12397796 -0.13191423 -1.62328545  0.64667545]
 [-0.35627076 -1.74314104 -0.59664964 -0.58859438 -0.8738823   0.02971382]]
Your answer:
[[-21.207  -5.373 -20.933  -9.179 -11.319 -17.812]
 [ -1.995   7.906 -10.516   3.452   9.863  -7.24 ]
 [  5.479   1.115   9.244   0.453   5.656   7.089]
 [ -7.413  -7.416   0.363  -5.573  -6.736  -0.848]
 [-11.261  -9.937  -4.848  -8.915 -13.378  -5.761]
 [  3.548  10.036  -2.244   1.604  12.113  -2.557]
 [  4.888  -5.814   2.407   3.228  -4.232   3.71 ]
 [  1.248  18.894  -6.409   3