<a href="https://colab.research.google.com/github/chahatpatel2003/CSCI-167/blob/main/notebook_10_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
np.set_printoptions(precision=3, floatmode="fixed")
torch.set_printoptions(precision=3)

def conv_pytorch(image, conv_weights, stride=1, pad=1):
    image_tensor = torch.from_numpy(image)
    conv_weights_tensor = torch.from_numpy(conv_weights)
    output_tensor = torch.nn.functional.conv2d(image_tensor, conv_weights_tensor, stride=stride, padding=pad)
    return output_tensor.numpy()

def conv_numpy_1(image, weights, pad=1):
    if pad != 0:
        image = np.pad(image, ((0,0),(0,0),(pad,pad),(pad,pad)),'constant')
    batchSize, channelsIn, imageHeightIn, imageWidthIn = image.shape
    channelsOut, channelsIn, kernelHeight, kernelWidth = weights.shape
    imageHeightOut = np.floor(1 + imageHeightIn - kernelHeight).astype(int)
    imageWidthOut  = np.floor(1 + imageWidthIn  - kernelWidth ).astype(int)
    out = np.zeros((batchSize, channelsOut, imageHeightOut, imageWidthOut), dtype=np.float32)
    for c_y in range(imageHeightOut):
        for c_x in range(imageWidthOut):
            for c_kernel_y in range(kernelHeight):
                for c_kernel_x in range(kernelWidth):
                    this_pixel_value = image[0, 0, c_y + c_kernel_y, c_x + c_kernel_x]
                    this_weight = weights[0, 0, c_kernel_y, c_kernel_x]
                    out[0, 0, c_y, c_x] += np.sum(this_pixel_value * this_weight)
    return out

np.random.seed(1)
n_batch = 1
image_height = 4
image_width = 6
channels_in = 1
kernel_size = 3
channels_out = 1
input_image = np.random.normal(size=(n_batch, channels_in, image_height, image_width))
conv_weights = np.random.normal(size=(channels_out, channels_in, kernel_size, kernel_size))
conv_results_pytorch = conv_pytorch(input_image, conv_weights, stride=1, pad=1)
print("PyTorch Results")
print(conv_results_pytorch)
print("Your results")
conv_results_numpy = conv_numpy_1(input_image, conv_weights)
print(conv_results_numpy)

def conv_numpy_2(image, weights, stride=1, pad=1):
    if pad != 0:
        image = np.pad(image, ((0,0),(0,0),(pad,pad),(pad,pad)),'constant')
    batchSize, channelsIn, imageHeightIn, imageWidthIn = image.shape
    channelsOut, channelsIn, kernelHeight, kernelWidth = weights.shape
    imageHeightOut = np.floor(1 + (imageHeightIn - kernelHeight) / stride).astype(int)
    imageWidthOut  = np.floor(1 + (imageWidthIn  - kernelWidth ) / stride).astype(int)
    out = np.zeros((batchSize, channelsOut, imageHeightOut, imageWidthOut), dtype=np.float32)
    for c_y in range(imageHeightOut):
        for c_x in range(imageWidthOut):
            base_y = c_y * stride
            base_x = c_x * stride
            for c_kernel_y in range(kernelHeight):
                for c_kernel_x in range(kernelWidth):
                    this_pixel_value = image[0, 0, base_y + c_kernel_y, base_x + c_kernel_x]
                    this_weight = weights[0, 0, c_kernel_y, c_kernel_x]
                    out[0, 0, c_y, c_x] += np.sum(this_pixel_value * this_weight)
    return out

np.random.seed(1)
n_batch = 1
image_height = 12
image_width = 10
channels_in = 1
kernel_size = 3
channels_out = 1
stride = 2
input_image = np.random.normal(size=(n_batch, channels_in, image_height, image_width))
conv_weights = np.random.normal(size=(channels_out, channels_in, kernel_size, kernel_size))
conv_results_pytorch = conv_pytorch(input_image, conv_weights, stride, pad=1)
print("PyTorch Results")
print(conv_results_pytorch)
print("Your results")
conv_results_numpy = conv_numpy_2(input_image, conv_weights, stride, pad=1)
print(conv_results_numpy)

def conv_numpy_3(image, weights, stride=1, pad=1):
    if pad != 0:
        image = np.pad(image, ((0,0),(0,0),(pad,pad),(pad,pad)),'constant')
    batchSize, channelsIn, imageHeightIn, imageWidthIn = image.shape
    channelsOut, channelsIn, kernelHeight, kernelWidth = weights.shape
    imageHeightOut = np.floor(1 + (imageHeightIn - kernelHeight) / stride).astype(int)
    imageWidthOut  = np.floor(1 + (imageWidthIn  - kernelWidth ) / stride).astype(int)
    out = np.zeros((batchSize, channelsOut, imageHeightOut, imageWidthOut), dtype=np.float32)
    for c_y in range(imageHeightOut):
        for c_x in range(imageWidthOut):
            base_y = c_y * stride
            base_x = c_x * stride
            for c_channel_out in range(channelsOut):
                for c_channel_in in range(channelsIn):
                    for c_kernel_y in range(kernelHeight):
                        for c_kernel_x in range(kernelWidth):
                            this_pixel_value = image[0, c_channel_in, base_y + c_kernel_y, base_x + c_kernel_x]
                            this_weight = weights[c_channel_out, c_channel_in, c_kernel_y, c_kernel_x]
                            out[0, c_channel_out, c_y, c_x] += np.sum(this_pixel_value * this_weight)
    return out

np.random.seed(1)
n_batch = 1
image_height = 4
image_width = 6
channels_in = 5
kernel_size = 3
channels_out = 2
input_image = np.random.normal(size=(n_batch, channels_in, image_height, image_width))
conv_weights = np.random.normal(size=(channels_out, channels_in, kernel_size, kernel_size))
conv_results_pytorch = conv_pytorch(input_image, conv_weights, stride=1, pad=1)
print("PyTorch Results")
print(conv_results_pytorch)
print("Your results")
conv_results_numpy = conv_numpy_3(input_image, conv_weights, stride=1, pad=1)
print(conv_results_numpy)

def conv_numpy_4(image, weights, stride=1, pad=1):
    if pad != 0:
        image = np.pad(image, ((0,0),(0,0),(pad,pad),(pad,pad)),'constant')
    batchSize, channelsIn, imageHeightIn, imageWidthIn = image.shape
    channelsOut, channelsIn, kernelHeight, kernelWidth = weights.shape
    imageHeightOut = np.floor(1 + (imageHeightIn - kernelHeight) / stride).astype(int)
    imageWidthOut  = np.floor(1 + (imageWidthIn  - kernelWidth ) / stride).astype(int)
    out = np.zeros((batchSize, channelsOut, imageHeightOut, imageWidthOut), dtype=np.float32)
    for c_batch in range(batchSize):
        for c_y in range(imageHeightOut):
            for c_x in range(imageWidthOut):
                base_y = c_y * stride
                base_x = c_x * stride
                for c_channel_out in range(channelsOut):
                    for c_channel_in in range(channelsIn):
                        for c_kernel_y in range(kernelHeight):
                            for c_kernel_x in range(kernelWidth):
                                this_pixel_value = image[c_batch, c_channel_in, base_y + c_kernel_y, base_x + c_kernel_x]
                                this_weight = weights[c_channel_out, c_channel_in, c_kernel_y, c_kernel_x]
                                out[c_batch, c_channel_out, c_y, c_x] += np.sum(this_pixel_value * this_weight)
    return out

np.random.seed(1)
n_batch = 2
image_height = 4
image_width = 6
channels_in = 5
kernel_size = 3
channels_out = 2
input_image = np.random.normal(size=(n_batch, channels_in, image_height, image_width))
conv_weights = np.random.normal(size=(channels_out, channels_in, kernel_size, kernel_size))
conv_results_pytorch = conv_pytorch(input_image, conv_weights, stride=1, pad=1)
print("PyTorch Results")
print(conv_results_pytorch)
print("Your results")
conv_results_numpy = conv_numpy_4(input_image, conv_weights, stride=1, pad=1)
print(conv_results_numpy)


PyTorch Results
[[[[-0.929 -2.760  0.716  0.114  0.560 -0.387]
   [-1.515  0.283  1.008  0.466 -1.094  2.004]
   [-1.634  3.555 -2.154 -0.892 -1.856  2.299]
   [ 0.565 -0.947 -0.629  2.996 -1.811 -0.533]]]]
Your results
[[[[-0.929 -2.760  0.716  0.114  0.560 -0.387]
   [-1.515  0.283  1.008  0.466 -1.094  2.004]
   [-1.634  3.555 -2.154 -0.892 -1.856  2.299]
   [ 0.565 -0.947 -0.629  2.996 -1.811 -0.533]]]]
PyTorch Results
[[[[-0.809 -4.550 -5.486 -9.506 -4.512]
   [-0.055  1.145 -5.388 -3.910  0.097]
   [-0.186  0.660  1.630  2.275  4.874]
   [ 2.386 -0.225  3.288 -4.239 -1.403]
   [ 0.825  1.710 -3.246  3.246  1.709]
   [ 0.809  3.695  3.491 -2.113 -2.714]]]]
Your results
[[[[-0.809 -4.550 -5.486 -9.506 -4.512]
   [-0.055  1.145 -5.388 -3.910  0.097]
   [-0.186  0.660  1.630  2.275  4.874]
   [ 2.386 -0.225  3.288 -4.239 -1.403]
   [ 0.825  1.710 -3.246  3.246  1.709]
   [ 0.809  3.695  3.491 -2.113 -2.714]]]]
PyTorch Results
[[[[ -0.785   5.463  -2.480   5.026  -3.594   7.785]
   [ 